#!/usr/bin/env python

from os import environ as ENV
from urlparse import urlparse
from sys import argv

from pymongo import Connection


MONGOLAB_URI = ENV[ 'MONGOLAB_URI' ]


conn = Connection( MONGOLAB_URI )
db = conn[ urlparse( MONGOLAB_URI ).path[ 1: ] ] 

if len( argv ) > 1:
	if argv[ 1 ] == '-e':
		for entry in db[ 'error-log' ].find():
			print entry['timestamp'].as_datetime(), entry['message']
	elif argv[ 1 ] == '-a':
		for entry in db[ 'application-log' ].find():
			print entry['timestamp'].as_datetime(), entry['message']
else:
	for entry in db[ 'access-log' ].find():
		print entry['message']
