#!/usr/bin/env python

# Copyright 2011, Massimo Santini <santini@dsi.unimi.it>
# 
# This file is part of "heroku-log4mongo".
# 
# "No Fuss Bookmarks" is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
# 
# "heroku-log4mongo" is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
# 
# You should have received a copy of the GNU General Public License along with
# "heroku-log4mongo". If not, see <http://www.gnu.org/licenses/>.

from urlparse import urlparse
from sys import argv

from pymongo import Connection

# this is horrible, works if set_env outputs MONGOLAB_URI on the first line!
MONGOLAB_URI = open( '.env' ).readline().strip().split( '=' )[ 1 ] 

conn = Connection( MONGOLAB_URI )
db = conn[ urlparse( MONGOLAB_URI ).path[ 1: ] ] 

if len( argv ) > 1:
	if argv[ 1 ] == '-e':
		for entry in db[ 'error-log' ].find():
			print entry['timestamp'].as_datetime(), entry['message']
	elif argv[ 1 ] == '-a':
		for entry in db[ 'application-log' ].find():
			print entry['timestamp'].as_datetime(), entry['message']
else:
	for entry in db[ 'access-log' ].find():
		print entry['message']
