#!/bin/bash

# Copyright 2011, Massimo Santini <santini@dsi.unimi.it>
# 
# This file is part of "heroku-log4mongo".
# 
# "No Fuss Bookmarks" is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
# 
# "heroku-log4mongo" is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
# 
# You should have received a copy of the GNU General Public License along with
# "heroku-log4mongo". If not, see <http://www.gnu.org/licenses/>.

heroku config -s | grep 'MONGOLAB_URI' > .env
echo 'VERSION=developement' >> .env
